//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.06 at 10:07:18 AM CEST 
//


package no.nav.model.databatch;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.nav.model.dataBatch package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.nav.model.dataBatch
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataUnit }
     * 
     */
    public DataUnit createDataUnit() {
        return new DataUnit();
    }

    /**
     * Create an instance of {@link DataUnit.FormTask }
     * 
     */
    public DataUnit.FormTask createDataUnitFormTask() {
        return new DataUnit.FormTask();
    }

    /**
     * Create an instance of {@link DataUnit.Approvers }
     * 
     */
    public DataUnit.Approvers createDataUnitApprovers() {
        return new DataUnit.Approvers();
    }

    /**
     * Create an instance of {@link DataBatch }
     * 
     */
    public DataBatch createDataBatch() {
        return new DataBatch();
    }

    /**
     * Create an instance of {@link DataUnits }
     * 
     */
    public DataUnits createDataUnits() {
        return new DataUnits();
    }

    /**
     * Create an instance of {@link MetadataList }
     * 
     */
    public MetadataList createMetadataList() {
        return new MetadataList();
    }

    /**
     * Create an instance of {@link Attachments }
     * 
     */
    public Attachments createAttachments() {
        return new Attachments();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link DataUnit.FormTask.SOEncryptedSymmetricdKey }
     * 
     */
    public DataUnit.FormTask.SOEncryptedSymmetricdKey createDataUnitFormTaskSOEncryptedSymmetricdKey() {
        return new DataUnit.FormTask.SOEncryptedSymmetricdKey();
    }

    /**
     * Create an instance of {@link DataUnit.FormTask.Form }
     * 
     */
    public DataUnit.FormTask.Form createDataUnitFormTaskForm() {
        return new DataUnit.FormTask.Form();
    }

    /**
     * Create an instance of {@link DataUnit.Approvers.Approver }
     * 
     */
    public DataUnit.Approvers.Approver createDataUnitApproversApprover() {
        return new DataUnit.Approvers.Approver();
    }

}
